import "~/styles/globals.css";
import { SessionProvider } from "next-auth/react";

import { GeistSans } from "geist/font/sans";
import { type Metadata } from "next";
import TopNav from "~/components/topnav";
import { auth } from "~/server/auth/auth";
import LoggedInLayout from "~/components/logged-in-layout";
import LoggedOutLayout from "~/components/logged-out-layout";

export const metadata: Metadata = {
  title: "Create T3 App",
  description: "Generated by create-t3-app",
  icons: [{ rel: "icon", url: "/favicon.ico" }],
};

export default async function RootLayout({
  children,
}: Readonly<{ children: React.ReactNode }>) {
  const session = await auth();
  return (
    <SessionProvider>
      <html lang="en" className={`${GeistSans.variable}`}>
        <body className="flex min-h-screen flex-col">
          {session ? (
            <LoggedInLayout>{children}</LoggedInLayout>
          ) : (
            <LoggedOutLayout>{children}</LoggedOutLayout>
          )}
        </body>
      </html>
    </SessionProvider>
  );
}
